### PR TITLE
Insert alt attribute.

### PR DESCRIPTION
**Pull request by gmattar**

### CODE REVIEW

**Comment by lharv076** [comment]
@gmattar When can we deploy?

**Comment by gmattar** [comment]
I can deploy it now. Just give me the ok

**Comment by lharv076** [comment]
Ok, let's do it. Thanks!

**Comment by lharv076** [comment]
@gmattar The ca3.opennorth.ca app is broken, but not the ca1.opennorth.ca one.

http://app.citizenbudget.com/admin/login
http://ca1.opennorth.ca/admin

**Comment by gmattar** [comment]
the ca3 deployment is not finished yet

**Comment by gmattar** [comment]
try again now

**Comment by gmattar** [comment]
Are you still having problems?  Can I start ca1 deploy?

**Comment by lharv076** [comment]
It works! Thanks :)

**Comment by gmattar** [comment]
ok. I'll start ca1 now.

**Comment by lharv076** [comment]
perfect

**Pull request merged**
