### PR TITLE
Fix slider value update.

### PR DESCRIPTION
**Pull request by gmattar**

### CODE REVIEW

**Comment by lharv076** [comment]
@jpmckinney Are you able to deploy onto both servers? I can't get a hold of Phil.

**Comment by phildionne** [comment]
I'm deploying right now.

**Comment by lharv076** [comment]
It works - Thank you!

**Comment by lharv076** [comment]
@claudioccm @gmattar 
Is it possible to have the numbers displayed as dollar figures again? Either 207k or 207,000. (tok.citizenbudget.com)

Also, when you access a consultation for the first time (ex: http://westkelowna.citizenbudget.com/?token=sSdbiwxm9YwqS173CbFP), the figures just show "1". The numbers only appear once you start moving the slider, but the default value should be there from the get-go.

Thanks!

**Pull request merged**
