### PR TITLE
Restore custom "changeSlider" functionality.

### PR DESCRIPTION
**Pull request by gmattar**

### CODE REVIEW

**Comment by gmattar** [comment]
This also fixes the summary table in aurora.citizenbudget.com.

**Comment by lharv076** [comment]
@gmattar Can you revert? It broke the application and I can't do any other tests until Monday.

Wait until I confirm before you merge anything. Thanks!

**Comment by gmattar** [comment]
Sorry for that,  I already found the problem, it was a typo. 
I'll do it again Monday when you give the green light.

**Comment by lharv076** [comment]
@gmattar Ready when you are!

**Pull request merged**
