### PR TITLE
Fix slider's initial values.

### PR DESCRIPTION
**Pull request by gmattar**

### CODE REVIEW

**Comment by lharv076** [comment]
@gmattar Tell me when it's ready so we can merge and deploy. Does it also add in the default position marker?

**Comment by gmattar** [comment]
It is ready to merge. It also add the initial marker and the tootltip value update while dragging the slider

**Comment by lharv076** [comment]
@gmattar There's no tooltip! (see tok.citizenbudget.com)

**Comment by lharv076** [comment]
@gmattar The tooltip is fixed, that's great.

I'm having an issue with a live consultation now though, the message in the message bar isn't displaying. (tok.citizenbudget.com)

Very urgent

Thanks!

**Comment by lharv076** [comment]
If it's the custom JS, can you fix it here

http://ca1.opennorth.ca/admin/questionnaires/570fc5b0a7ceae927000005c

**Comment by gmattar** [comment]
I can look it right now. Is this message bar the pink/yellow one fixed on top?

**Comment by lharv076** [comment]
Exactly. It's a problem with very large deficits and very large surplus.
Middle range deficits/surpluses work.

On Thu, May 5, 2016 at 1:43 PM, Guilherme Mattar Bastos <
notifications@github.com> wrote:

> I can look it right now. Is this message bar the pink/yellow one fixed on
> top?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/opennorth/citizenbudgetapp.com/pull/122#issuecomment-217222694>
>



-- 
*​*

*If you're at the GFOA in Toronto come by ​the Exhibit Hall ​and say hi
to ​us at booth #508! *

*Laurence Harvey Leclerc*
Product Development Manager
Open North / Citizen Budget
1.888.750.4980 x. 706

Visit our NEW website - http://citizenbudget.com
@opennorth

**Comment by gmattar** [comment]
In the application, each language have 5 default values for the message bar: 
`large_surplus`
`surplus`
`balanced`
`deficit`
`large_deficit`

The custom javascript is overriding the English but only setting `surplus`, `balanced`, `deficit`. `large_surplus' and `large_deficit` are missing.
You can add the text there or paste it here and I can do it myself.

**Comment by lharv076** [comment]
Thank you! I fixed it myself. 

I appreciate the quick turnaround :)

**Pull request merged**
