### PR TITLE
Fix logo size

### LINKED ISSUE #99: Blurry header
@claudioccm 

The images on desktop are blurry for the header (e.g. http://westkelowna.citizenbudget.com/)

The original image is 940px wide so I think the application is causing a distortion.

### PR DESCRIPTION
**Pull request by phildionne**
Resolves #99

### CODE REVIEW

**Comment by phildionne** [comment]
The goal is to ensure images have the proper dimensions before being uploaded. We then render "as is" in the response view.

**Comment by phildionne** [comment]
I'm merging this and deploying on laurence's demand.

**Comment by lharv076** [comment]
@phildionne I don't think it worked. I changed the header for http://westkelowna.citizenbudget.com/?token=sSdbiwxm9YwqS173CbFP and it's still blurry, even though the image is 940px wide.

**Comment by lharv076** [comment]
Weird. It worked for Guelph.

**Pull request merged**
