### PR TITLE
Add conditional questions

### PR DESCRIPTION
**Pull request by phildionne**
I might have missed a few subtleties but overall it seems to work pretty well! Looking to have some feedback.

### CODE REVIEW

**Comment by jpmckinney** [comment]
Looks good to me!

**Comment by lharv076** [comment]
@jpmckinney Can we try it out today?

**Comment by jpmckinney** [comment]
Deployed

**Comment by lharv076** [comment]
@phildionne This looks great. I made a demo to test it out:

http://app.citizenbudget.com/?token=BGcLoPzzysKULbRwBLJM

Off the bat, a couple things stand out:

1. The Yes/No widget doesn't seem to be working well in the conditional question sections.
2. If I answer some questions in one criteria, and then switch to another, the answers are saved (I like that). If I hit submit, will it submit all the "hidden" question answers? (it shouldn't)

Thanks!
Laurence

**Comment by phildionne** [comment]
Looking into both issues, right now it would submit the "hidden" questions.

**Comment by lharv076** [comment]
@phildionne @claudioccm 

I added a conditional question to the mobile test and it's not adapted (the questions aren't hidden), so that will also need to be fixed.

test.citizenbudget.com (the last section)

**Comment by phildionne** [comment]
Sorry about PR duplication, I'm a bit rusty with the whole git + github collaboration flow.

**Comment by phildionne** [comment]
#91 fixes inactive conditional questions being submitted. I've seriously looked into the boolean iphone style widget bug and can't determine what's happening. I know for sure it is related to the visibility of the `tr` element and the `iphone-style-checkboxes.js.coffee` file but that doesn't solve it.

**Comment by phildionne** [comment]
@lharv076 

About the conditional question on mobile, we should first start by merging #90 and investigate from there.

**Pull request merged**
