### PR TITLE
More mobile adjustments.

### PR DESCRIPTION
**Pull request by gmattar**

### CODE REVIEW

**Comment by lharv076** [comment]
@jpmckinney 

Can you merge this when you have a minute?

Thanks!

**Comment by lharv076** [comment]
@claudioccm 

Claudio, I'm extremely happy with this newest version! It looks amazing. There are still two very small bugs:

(see test.citizenbudget.com for live version)

1. The header image isn't fitting the screen properly. Is it because I add the image through CSS in the application, rather than using the specific field for it? 

2. There's a very large empty space between the last question and the "submit your choices" section. It could be because it's the new conditional question feature?

Thanks!
Laurence

**Comment by claudioccm** [comment]
Lauren,
the header image is because you are adding it with css. We will fix that
once we start adding those images in a better way.
this space, can be the conditional question. I didn't see it on my local
version here.

**Comment by lharv076** [comment]
Ok great, yes I know that fixing the logo/header features on the app was also part of Phase 1 development so looking forward to seeing that roll out. 

For the empty space, it only shows up on a mobile device, not on the desktop. If you pull up test.citizenbudget.com on your phone, you will see it.

**Comment by lharv076** [comment]
I switched the image for one using the logo input feature on the application. It works well on mobile, but the problem is on the desktop version (it doesn't take up the whole width of the screen).

**Comment by lharv076** [comment]
@claudioccm 

I did a test with the tax version (see budgetfeedback.tol.ca on your phone). A few bugs:

1. The Property Assessment box doesn't show the default value, and text doesn't appear when you overwrite it with another value. The functionality of it works though, all the numbers adjusted when I overwrote the default value. 

2. The black message bar doesn't follow the user as they go through the exercise, and isn't fitted to the screen.

3. The preference summary chart doesn't display properly

4. I added an impact statement to the first question to see how it looks. It works well! Can we just increase the text size so that it goes along with the rest of the mobile style?

Everything else works great :D

Thanks!
Laurence

**Comment by claudioccm** [comment]
Thanks! I will check that

**Comment by lharv076** [comment]
@claudioccm Just another note that could help you. I think that the headers in desktop consultations aren't doing the width of the consultation anymore because the changes in #92 stretched out the whole consultation to be wider than 940px. Before, it was more centered in the screen. (see buildabudget.ca for example) 

I'd prefer we go back to the regular 940px width than having it full screen on desktop.

**Comment by lharv076** [comment]
@claudioccm Hi Claudio,

Any updates on this? Can we have some of these bugs fixed by Friday?

Thanks,
Laurence

**Comment by claudioccm** [comment]
we sent a PR this afternoon, with some of them fixed. I think teh only one
that is not fixed, is because we couldn't replicate the bug

**Comment by lharv076** [comment]
@claudioccm 

Hey Claudio,

I'm happy with how you fixed the property assessment box and the messaging. Both very important features! I'm getting really excited with how close we're getting to being done :)

A few bugs, in order of priority:

**On desktop (see test.citizenbudget.com) :**

1. In Trello, it looks like you have the header/logo attachment bug fixed and in the "next deploy" queue. Can we do that this week? The header is showing up very nicely on mobile, but on the desktop version it isn't taking up the width of the page.

**On mobile (see budgetfeedback.tol.ca) :**

2. The preference summary chart (at the bottom) isn't showing up properly.

3. The impact bar styling needs to be brought up to par with the rest of what you've done so far. I added one to the first question. Move the slider and you'll see the impact statement appear. It needs to stand out a bit more.

**On mobile (see buildabudget.ca) :**

We really went above and beyond with customizations for this client, so I understand that it's difficult to adapt the mobile application, but I'd like us to try. 

4. The "i" for learn more is appearing really large in the description under "Base budget exercise" and "Strategic Investments".

5. I added dynamic pie charts under each section and they're slightly going off screen and overlapping with the image. 

6. Same as for #2, the preference summary chart isn't showing up properly.

Let me know if you have any questions! 

Thanks,
Laurence

**Comment by claudioccm** [comment]
```
.pics, 
#learn { display: none; }
```

**Pull request merged**
