### PR TITLE
Patching the latest PR

### PR DESCRIPTION
**Pull request by claudioccm**

### CODE REVIEW

**Comment by jpmckinney** [comment]
@phildionne Now that you can deploy, do you want to try merging and deploying this?

**Comment by phildionne** [comment]
Sure, since I'm new to this deployment flow I'll just make sure @jpmckinney approves it before doing it:

1. Merge branch on master and close PR
2. `git checkout master`
3. `git pull --rebase`
4. `git push ca1 master -f`
5. `git push ca3 master -f`

**Comment by jpmckinney** [comment]
No need for the `-f` on push, otherwise good!

**Comment by lharv076** [comment]
@phildionne lets merge this today plz!

**Comment by phildionne** [comment]
Deployed

**Comment by lharv076** [comment]
@claudioccm EXCELLENT! We're done with mobile :) Thanks!

**Pull request merged**
